//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by @thetay
//

import UIKit

// MARK: View
class ___VARIABLE_sceneName___ViewController: UIViewController {
    var output: ___VARIABLE_sceneName___ViewControllerOutputProtocol!
    var router: ___VARIABLE_sceneName___Router!
    var viewModel: ___VARIABLE_sceneName___Model.ViewModel?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchDataOnLoad()
        setupView()
    }
    
    // MARK: Fetch ___VARIABLE_productName:identifier___
    private func fetchDataOnLoad() {
        // NOTE: Ask the Interactor to do some work
        
    }
    
    // MARK: SetupUI
    private func setupView() {
        
    }
}

// MARK: Connect View, Interactor, and Presenter
extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___PresenterOutputProtocol {
    
}
