//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Savvycom
//

class ___VARIABLE_sceneName___Interactor/*: ___VARIABLE_sceneName___ViewControllerDataSource */ {
    var output: ___VARIABLE_sceneName___InteractorOutputProtocol!
    var worker: ___VARIABLE_sceneName___Worker = ___VARIABLE_sceneName___Worker()
}

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___ViewControllerOutputProtocol {

}

