//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by @thetay
//

class ___VARIABLE_sceneName___Presenter {
    weak var output: ___VARIABLE_sceneName___PresenterOutputProtocol!
}

extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___InteractorOutputProtocol {
  
}
